# Generated by Django 5.2.3 on 2025-06-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Surname', models.CharField(max_length=32)),
                ('Partonymic', models.CharField(max_length=32, null=True)),
                ('Email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Question', models.TextField()),
                ('Points_Answer_Yes', models.IntegerField()),
                ('Points_Answer_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase_EXHAUSTION',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Record', models.DateTimeField(auto_now_add=True)),
                ('Symptom1', models.IntegerField(null=True)),
                ('Symptom2', models.IntegerField(null=True)),
                ('Symptom3', models.IntegerField(null=True)),
                ('Symptom4', models.IntegerField(null=True)),
                ('SymptomSum', models.IntegerField(null=True)),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EXHAUSTION', to='api.people')),
            ],
        ),
        migrations.CreateModel(
            name='Phase_RESISTANCE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Record', models.DateTimeField(auto_now_add=True)),
                ('Symptom1', models.IntegerField(null=True)),
                ('Symptom2', models.IntegerField(null=True)),
                ('Symptom3', models.IntegerField(null=True)),
                ('Symptom4', models.IntegerField(null=True)),
                ('SymptomSum', models.IntegerField(null=True)),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RESISTANCE', to='api.people')),
            ],
        ),
        migrations.CreateModel(
            name='Phase_VOLTAGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Record', models.DateTimeField(auto_now_add=True)),
                ('Symptom1', models.IntegerField(null=True)),
                ('Symptom2', models.IntegerField(null=True)),
                ('Symptom3', models.IntegerField(null=True)),
                ('Symptom4', models.IntegerField(null=True)),
                ('SymptomSum', models.IntegerField(null=True)),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VOLTAGE', to='api.people')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Burnout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Record', models.DateTimeField(auto_now_add=True)),
                ('Summary_Value', models.IntegerField()),
                ('EXHAUSTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Burnout', to='api.phase_exhaustion')),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Burnout', to='api.people')),
                ('RESISTANCE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Burnout', to='api.phase_resistance')),
                ('VOLTAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Burnout', to='api.phase_voltage')),
            ],
        ),
    ]
