# Generated by Django 5.2.3 on 2025-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='TG_ID',
            field=models.CharField(default='tg', max_length=64),
            preserve_default=False,
        ),
    ]
