# Generated by Django 5.2.3 on 2025-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_people_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
