# Generated by Django 5.2.3 on 2025-07-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_people_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Partonymic',
            new_name='Patronymic',
        ),
    ]
