# Generated by Django 5.2.3 on 2025-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_partonymic_people_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_burnout',
            name='EXHAUSTION',
        ),
        migrations.RemoveField(
            model_name='phase_resistance',
            name='People_ID',
        ),
        migrations.RemoveField(
            model_name='test_burnout',
            name='RESISTANCE',
        ),
        migrations.RemoveField(
            model_name='phase_voltage',
            name='People_ID',
        ),
        migrations.RemoveField(
            model_name='test_burnout',
            name='VOLTAGE',
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test_burnout',
            options={'verbose_name': 'Пройденный тест', 'verbose_name_plural': 'Пройденные тесты'},
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='Voltage_symptom1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='Voltage_symptom2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='Voltage_symptom3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='Voltage_symptom4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='Voltage_symptomSum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='exhaustion_symptom1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='exhaustion_symptom2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='exhaustion_symptom3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='exhaustion_symptom4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='exhaustion_symptomSum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='resistance_symptom1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='resistance_symptom2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='resistance_symptom3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='resistance_symptom4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_burnout',
            name='resistance_symptomSum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phase_EXHAUSTION',
        ),
        migrations.DeleteModel(
            name='Phase_RESISTANCE',
        ),
        migrations.DeleteModel(
            name='Phase_VOLTAGE',
        ),
    ]
