# Generated by Django 5.2.3 on 2025-08-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_test_burnout_exhaustion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everyweek_Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Phase', models.TextField(verbose_name='Фаза задания')),
                ('Name', models.TextField(verbose_name='Название задания')),
                ('Text', models.TextField(verbose_name='Текст задания')),
            ],
            options={
                'verbose_name': 'Еженедельное задание',
                'verbose_name_plural': 'Еженедельные задания',
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='Birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Email',
            field=models.CharField(max_length=64, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Patronymic',
            field=models.CharField(max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Surname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Name_Question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Points_Answer_No',
            field=models.IntegerField(verbose_name='Баллов за "Нет"'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Points_Answer_Yes',
            field=models.IntegerField(verbose_name='Баллов за "Да"'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Date_Record',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='People_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Burnout', to='api.people', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Summary_Value',
            field=models.IntegerField(verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Voltage_symptom1',
            field=models.IntegerField(verbose_name='Переж. обст.'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Voltage_symptom2',
            field=models.IntegerField(verbose_name='Неуд. собой'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Voltage_symptom3',
            field=models.IntegerField(verbose_name='Загнанность'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Voltage_symptom4',
            field=models.IntegerField(verbose_name='Тревога'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='Voltage_symptomSum',
            field=models.IntegerField(verbose_name='Сумма напряжения'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='exhaustion_symptom1',
            field=models.IntegerField(verbose_name='Эм. дефицит'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='exhaustion_symptom2',
            field=models.IntegerField(verbose_name='Эм. отстр.'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='exhaustion_symptom3',
            field=models.IntegerField(verbose_name='Лич. отстр.'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='exhaustion_symptom4',
            field=models.IntegerField(verbose_name='Психосоматика'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='exhaustion_symptomSum',
            field=models.IntegerField(verbose_name='Сумма истощения'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='resistance_symptom1',
            field=models.IntegerField(verbose_name='Эм. реакция'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='resistance_symptom2',
            field=models.IntegerField(verbose_name='Эм. дезор.'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='resistance_symptom3',
            field=models.IntegerField(verbose_name='Расш. сферы'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='resistance_symptom4',
            field=models.IntegerField(verbose_name='Редукция'),
        ),
        migrations.AlterField(
            model_name='test_burnout',
            name='resistance_symptomSum',
            field=models.IntegerField(verbose_name='Сумма резистенции'),
        ),
    ]
