# Generated by Django 5.2.3 on 2025-08-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250817_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everyweek_tasks',
            options={'verbose_name': 'Тип еженедельного задания', 'verbose_name_plural': 'Типы еженедельного задания'},
        ),
        migrations.CreateModel(
            name='Answers_Everyweek_Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Record', models.DateTimeField(auto_now_add=True, verbose_name='Дата взятия задания')),
                ('Stars', models.IntegerField(blank=True, null=True, verbose_name='Количество звёзд')),
                ('Comments', models.TextField(blank=True, null=True, verbose_name='Комментарий к заданию')),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Answers_everyweek_task', to='api.everyweek_tasks', verbose_name='Тип еженедельного задания')),
                ('TestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers_everyweek_task', to='api.test_burnout', verbose_name='Тест выгорания')),
            ],
            options={
                'verbose_name': 'Еженедельное задание',
                'verbose_name_plural': 'Еженедельные задания',
            },
        ),
    ]
