# Generated by Django 5.2.3 on 2025-08-27 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


def create_settings_forward(apps, schema_editor):
    People = apps.get_model("api", "People")
    Options = apps.get_model("api", "Options")
    for p in People.objects.filter(options__isnull=True):
        Options.objects.create(People_ID=p)

def create_settings_backward(apps, schema_editor):
    Options = apps.get_model("api", "Options")
    Options.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_everyweek_tasks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('People_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='options', serialize=False, to='api.people', verbose_name='Пользователь')),
                ('Notification_Day_Time', models.TimeField(blank=True, default=datetime.time(20, 30), null=True, verbose_name='Уведомления на ежедневные задания')),
                ('Notification_Week_Time', models.TimeField(blank=True, default=datetime.time(19, 0), null=True, verbose_name='Уведомления на еженедельные задания')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователя',
            },
        ),
        migrations.RunPython(create_settings_forward, create_settings_backward),
    ]
