# Generated by Django 5.2.3 on 2025-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers_everyweek_tasks',
            name='NotificationSent',
            field=models.BooleanField(default=False, verbose_name='Уведомление было отправлено?'),
        ),
    ]
