# Generated by Django 5.2.3 on 2025-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_answers_everyweek_tasks_notificationsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='Notification_Day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='options',
            name='Notification_Week',
            field=models.BooleanField(default=True),
        ),
    ]
