# Generated by Django 5.2.3 on 2025-09-15 20:07

from django.db import migrations, connection


def __executeSQL(script):
    try:
        with connection.cursor() as cursor:
            scripts = script.split(';')
            for script in scripts:
                if script:
                    cursor.execute(f'{script};')
        return {'result': 'success'}
    except Exception:
        return {'result': str(Exception)}


def fill_tables(apps, schema_editor):
    SQL_SCRIPTS = ['Everyweek_task_fill.sql']
    for script in SQL_SCRIPTS:
        with open(f'api/SQL/{script}', encoding='utf-8') as f:
            content = f.read()
            result = __executeSQL(content)

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0011_options_notification_day_options_notification_week'),
    ]

    operations = [
        migrations.RunPython(fill_tables),
    ]
