# Generated by Django 5.2.3 on 2025-09-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_full_data_migration_of_everyweek_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(verbose_name='Текст уведомления')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Scheduled_at', models.DateTimeField(verbose_name='Когда надо отправить')),
                ('Sent', models.BooleanField(default=False, verbose_name='Уже отправлено')),
                ('Sent_at', models.DateTimeField(blank=True, null=True)),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.people')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'indexes': [models.Index(fields=['Sent', 'Scheduled_at'], name='api_notific_Sent_963276_idx')],
            },
        ),
    ]
