# Generated by Django 5.2.3 on 2025-09-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notificationevent'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationevent',
            name='api_notific_Sent_963276_idx',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='Scheduled_at',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='Sent',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='Sent_at',
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['Created_at'], name='api_notific_Created_698915_idx'),
        ),
    ]
