# Generated by Django 5.2.3 on 2025-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_notificationevent_api_notific_sent_963276_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Email',
            field=models.CharField(max_length=64, null=True, verbose_name='Эл. почта'),
        ),
    ]
