# Generated by Django 5.2.3 on 2025-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_people_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Patronymic',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Surname',
        ),
        migrations.AddField(
            model_name='people',
            name='Nickname',
            field=models.CharField(default=2000, max_length=32, verbose_name='Псевдоним'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='Work_Experience',
            field=models.IntegerField(default=2000, verbose_name='Стаж'),
            preserve_default=False,
        ),
    ]
