# Generated by Django 5.2.3 on 2025-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_people_name_remove_people_patronymic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='Notification_Day_Time',
        ),
        migrations.RemoveField(
            model_name='options',
            name='Notification_Week_Time',
        ),
        migrations.AlterField(
            model_name='people',
            name='Email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Эл. почта'),
        ),
    ]
