# Generated by Django 5.2.3 on 2025-10-02 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_options_notification_day_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='Notification_Day',
            field=models.BooleanField(default=True, verbose_name='Ежедневные уведомления'),
        ),
        migrations.AlterField(
            model_name='options',
            name='Notification_Week',
            field=models.BooleanField(default=True, verbose_name='Еженедельные уведомления'),
        ),
        migrations.CreateModel(
            name='Answers_Everyday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Emotional_Condition', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Эмоциональное состояние')),
                ('Physical_Condition', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Физическое состояние')),
                ('Burnout', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Выгорание')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('People_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers_Everyday', to='api.people')),
            ],
        ),
    ]
