# Generated by Django 5.2.3 on 2025-10-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_options_notification_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers_everyday',
            options={'verbose_name': 'Ежедневное задание', 'verbose_name_plural': 'Ежедневные задания'},
        ),
        migrations.RemoveField(
            model_name='answers_everyweek_tasks',
            name='NotificationSent',
        ),
    ]
